[package]
name = "shock-convert"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
shock-convert-core = { version = "0.1.0", path = "../core" }
toml = "1.1.6"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Console", "Win32_UI_Shell", "Win32_System_Threading"] }
winreg = "0.56.0"
winrt-notification = "0.5.1"
